In [109]:
import torch
print(torch.__version__)

2.9.0+cpu


In [110]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU.")

GPU not available. Using CPU.


# Creating a Tensor

In [111]:
#using empty
a=torch.empty(2,3)
print(a)

tensor([[1.9833e-24, 0.0000e+00, 1.1806e-23],
        [0.0000e+00, 1.3863e+00, 1.1080e+27]])


In [112]:
#using zeros
b=torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [113]:
#using ones
c=torch.ones(2,3)
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [114]:
#using rand
d=torch.rand(2,3)
print(d)

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [115]:
#manual_seed
torch.manual_seed(100)
e1=torch.rand(2,3)
print(e1)
torch.manual_seed(100)
e2=torch.rand(2,3)
print(e2)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [116]:
#using tensor
f=torch.tensor([[1,2,3],[4,5,6]])
print(f)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [117]:
g=torch.arange(0,10,2)
print(g)

tensor([0, 2, 4, 6, 8])


In [118]:
#using linespace
h=torch.linspace(0,10,10)
print(h)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [119]:
#using eye
i=torch.eye(5)
print(i)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [120]:
#using full
j=torch.full((3,3),5)
print(j)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [121]:
x=torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [122]:
x.shape

torch.Size([2, 3])

In [123]:
y=torch.empty_like(x)
print(y)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [124]:
z=torch.zeros_like(x)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [125]:
y1=torch.ones_like(x)
print(y1)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [126]:
y2=torch.rand_like(x, dtype=torch.float32)
print(y2)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


# Tensor Data Types

In [127]:
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [128]:
x.dtype

torch.int64

In [129]:
#Now we specify datatype at the time of creation of tensor
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [130]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [131]:
#Using to() for converting datatype of existing tensor
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [132]:
x.dtype

torch.int64

In [133]:
x=x.to(torch.float32)

In [134]:
x.dtype

torch.float32

# Mathematical operations on tensors

**Scalar operations**

In [135]:
x=torch.rand(2,2)

In [136]:
print(x)

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])


In [137]:
#Addition
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [138]:
#Subtraction
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [139]:
#Multiplication
x*2

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])

In [140]:
#Division
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [141]:
#Mod
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [142]:
#Int division
(x*100)//3

tensor([[23., 26.],
        [13., 30.]])

In [143]:
#Power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

**Element wise operations**

In [144]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [145]:
print(a)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [146]:
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [147]:
#add
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [148]:
#subtraction
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [149]:
#Multiplication
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [150]:
#Division
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [151]:
#Power
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [152]:
#Mod
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [153]:
c=torch.tensor([1,-2,3,-4])

In [154]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [155]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [156]:
d=torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [157]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [158]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [159]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [160]:
#clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

**Reduction operation**

In [161]:
e=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [162]:
#sum of all items in the tensor
torch.sum(e)

tensor(24.)

In [163]:
#sum of items along the columns
torch.sum(e, dim=0)

tensor([ 8.,  0., 16.])

In [164]:
#sum of items along the rows
torch.sum(e,dim=1)

tensor([15.,  9.])

In [165]:
#mean
torch.mean(e)

tensor(4.)

In [166]:
#mean of items along the columns
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [167]:
#mean of items along the rows
torch.mean(e, dim=1)

tensor([5., 3.])

In [168]:
#median
torch.median(e)

tensor(0.)

In [169]:
#max
torch.max(e)

tensor(9.)

In [170]:
#min
torch.min(e)

tensor(0.)

In [171]:
#product of all items
torch.prod(e)

tensor(0.)

In [172]:
#standard deviation
torch.std(e)

tensor(4.4272)

In [173]:
#variance
torch.var(e)

tensor(19.6000)

In [174]:
#Argmax: Gives position of maximum value in the tensor
torch.argmax(e)

tensor(5)

In [175]:
#Argmin: Gives position of maximum value in the tensor
torch.argmin(e)

tensor(1)

# Matrix operations

In [176]:
f=torch.randint(size=(2,3), low=0, high=10)
g=torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [177]:
#Matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [178]:
#Dot product between two vectors
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

In [179]:
#Dot product
torch.dot(vector1, vector2)

tensor(11)

In [180]:
#Transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [181]:
#Determinant
h=torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
torch.det(h)

tensor(-110.)

In [182]:
#Inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

# Comparison operations

In [183]:
i=torch.randint(size=(2,3), low=0, high=10)
j=torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [184]:
#greater than
i>j

tensor([[ True,  True, False],
        [ True, False, False]])

In [185]:
#less than
i<j

tensor([[False, False,  True],
        [False,  True,  True]])

In [186]:
#equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [187]:
#not equal to
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [188]:
#greater than equal to
i>=j

tensor([[ True,  True, False],
        [ True, False, False]])

In [189]:
#less than equal to
i<=j

tensor([[False, False,  True],
        [False,  True,  True]])

# Special functions

In [190]:
k=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [191]:
#log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [192]:
#exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [193]:
#sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [194]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [195]:
#softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [196]:
#relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

# Inplace operations

In [197]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [198]:
m.add_(n)
print(m)
print(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [199]:
m.relu_()
print(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])


# Copying a Tensor

In [200]:
a=torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [201]:
b=a
print(id(a))
print("\n\n")
print(id(b))

132002682397920



132002682397920


In [202]:
b=a.clone()

In [203]:
print(id(a))
print("\n\n")
print(id(b))

132002682397920



132002682398960
